channels:
  - conda-forge
dependencies:
  - r-base=4.4
  - r-arrow
  - r-curl
  - r-data.table
  - r-digest
  - r-dplyr
  - r-ggplot2
  - r-httr2
  - r-jsonlite
  - r-matrix
  - r-mgcv
  - r-mvtnorm
  - r-readr
  - r-rprojroot
  - r-scales
  - r-targets
  - r-testthat
  - r-tidyselect
